[package]
name = "dodrio-ext"
version = "0.1.0"
authors = ["Raymond <extraymond@gmail.com>"]
edition = "2018"
description = "Extension that helps(me at least) increasing productivity when developing webapp ontop of dodrio and typed-html."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = { version = "0.2.56", features = ["serde"] }
dodrio = { git= "https://github.com/fitzgen/dodrio" }
wasm-bindgen-futures = { version = "0.3.27" }
typed-html = { version = "0.2.1", features = ["dodrio_macro"] }
js-sys = "0.3.28"
log = "0.4.8"
surf = { version = "1.0.3", features = ["wasm-client"] }
cfg-if = "0.1.10"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
async-trait = "0.1.21"
failure = "0.1.6"
futures = "0.3.1"

[dependencies.web-sys]
version = "0.3.28"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  "Worker",
  "WorkerGlobalScope",
  "WebSocket",
  "EventTarget",
  "BroadcastChannel"
]

[dev-dependencies]
wasm-bindgen-test = "0.3.1"
femme = "1.3.0"

[features]
default = ["console_error_panic_hook"]
release = ["console_error_panic_hook", "wee_alloc"]
