[workspace]
members = [
  "afterglow",
  "afterglow-router",
  "examples/buttons",
  "examples/tables",
  "examples/msg_bus"
]

# exclude = [
#   "examples/buttons",
#   "examples/tables",
#   "examples/msg_bus"
# ]
