[workspace]
members = [
  "afterglow",
  "afterglow-router",
  "afterglow-worker",
  "examples/buttons",
  "examples/tables",
  "examples/msg_bus",
  "examples/grid"
]

[patch.crates-io]
typed-html = { git = "https://github.com/bodil/typed-html" }